add an ability to update status of test plan
devolo/adaptavist pull request #10
Opened 2020-12-04 15:19 UTC by griddic

2020-12-07 13:08 UTC, SaneQ approved these changes

2020-12-08 11:16 UTC, Shutgun requested changes
LGTM, just a very minor thing to match the code style.

2020-12-08 11:16 UTC, Shutgun commented on adaptavist/adaptavist.py
> +            request_data['status'] = status
```suggestion
            request_data["status"] = status
```

2021-05-20 15:21 UTC, Shutgun commented
@griddic , I started a major rework of the code and added your request. I will close your MR now, but please stay tuned for the upcoming release.

2021-05-20 15:21 UTC, closed without merging