Adds compatibility with older tm4j API
devolo/adaptavist pull request #39
Opened 2023-05-11 21:41 UTC by KanoB

Older TM4J API do not have 'index' key in 'scriptResults' causing exceptions when sorting the list
Function affected: get_test_results
Related endpoint :  /testrun/{test_run_key}/testresults

2023-05-12 20:26 UTC, Shutgun commented
Hi @KanoB ,

thanks for your contribution. Could you tell me, which TM4J version you are using? If the index is missing: does the order of the results match the order of the steps?

2023-05-17 01:45 UTC, KanoB commented
Hi @Shutgun,
I can't see what version of TM4J is, since I am not admin on our JIRA instance. My thought is that it is v1 (https://support.smartbear.com/zephyr-scale-server/api-docs/v1/)

My test cases do not have steps, so I created one with steps and now I see that result does have the 'index' key inside scriptResults.
It seems to me that the proposed change will be good for those test cases that do not have steps.

The problem I see now, is that if multipe results are within a test case, it add attachments to first execution and not last when using `add_test_result_attachment()` method.

2023-05-17 02:07 UTC, KanoB commented
About `add_test_results_attachment()` issue that I mentioned above.
I have proposed change, but I'm not fully aware of all implication

`get_test_result()` must be modified to retrieve the last execution results and not first one available.

I did the change and run the tests and all 36 passed. Let me know if you want me to push that in same PR.

Regards, Claudio

2023-05-17 06:00 UTC, Shutgun commented
Supporting test cases without test steps is definitely something we should do. However, I feel like avoiding the sort completely then seems a better solution. Could you maybe post the payload of such a test case? Unfortunately I lost my access to a Jira instance with TM4J and I suppose you can post it quicker than my when asking my former colleges.

About the get_test_result method: I'd prefer a seperate PR for that :+1:

2023-05-23 04:37 UTC, KanoB commented
Here's a sample payload of get_test_results(): [payload](https://pastebin.com/0qi2ztyX)

The test cycle information has 2 test cases, one with steps and the other one without it.
When no steps are defined in test case, there is no index, because there's always only one element, so there is no need for sorting.

2023-05-23 06:17 UTC, Shutgun requested changes
Thanks, the payload helped my a lot to understand your approach. I assumed the payload to be different. However, I ran timeit on your solution and it turned out to be quit slow. Will not matter on single results, but if there are a lot it will sum up.

What do you thing about my suggestion? It seems to be 10x faster.

2023-05-23 06:17 UTC, Shutgun commented on adaptavist/adaptavist.py
> +            result["scriptResults"] = sorted(result["scriptResults"], key=lambda result: result.get("index", 0))
```suggestion
            if len(result["scriptResults"]) > 1:
                result["scriptResults"] = sorted(result["scriptResults"], key=lambda result: result["index"])
```

2023-05-23 14:56 UTC, Shutgun approved these changes

2023-05-23 14:58 UTC, Shutgun commented
Do you want to take care about ```add_test_results_attachment()``? I would then put both into the same release.

2023-05-23 14:59 UTC, merged