Sort test results to get latest execution results
devolo/adaptavist pull request #43
Opened 2023-05-27 16:46 UTC by KanoB

Proposed change sort the results by dictionary key name 'key'.
After putting some work I noticed the unittest for the function is using data that does not have that information.

I used 'key' item instead of dates because I noticed date can be deceiving when someone manually updates the information in JIRA. But the key is assigned by the system itself cannot be modified.

I created a new unit test to consider the fixture data with multiple execution results.

2023-06-02 14:05 UTC, Shutgun requested changes
Hi @KanoB , sorry it took me so long. I left a few suggestions.

2023-06-02 14:05 UTC, Shutgun commented on tests/test_adaptavist.py
> +    def test_get_test_result_when_multiple_results(self):
I guess, we can merge this with test_get_test_result, can't we?

2023-06-03 15:01 UTC, KanoB commented on tests/test_adaptavist.py
> +    def test_get_test_result_when_multiple_results(self):
Do you want to replace test `get_test_result()` to be done only with the new json data?

2023-06-03 15:22 UTC, KanoB commented on adaptavist/adaptavist.py
> +            return response.pop(0) or {}
I see, using max will do the trick, but still it'll throw KeyError exception if response data does not have 'key' in the results.
I guess all test results must have key item, but I did not want to assume that since you had sample data with that format (get_test_results.json). Do you want me to proceed with changes under this assumption?

2023-06-03 16:33 UTC, Shutgun commented on adaptavist/adaptavist.py
> +            return response.pop(0) or {}
Good point. I got the sample data from the official docs of the API, so I guess we should consider the possibility of a missing "key". Maybe sorting by "id" helps us here?

2023-06-03 16:34 UTC, Shutgun commented on tests/test_adaptavist.py
> +    def test_get_test_result_when_multiple_results(self):
Yes, I guess, that should be enough. Basically your data is more advanced so we shouldn't miss any case.

2023-06-18 18:46 UTC, KanoB commented on tests/test_adaptavist.py
> +    def test_get_test_result_when_multiple_results(self):
Sorry for late reply. I have commited changes with updated test data file.
I have updated the pytest to use new test data.

2023-06-18 18:46 UTC, KanoB commented on adaptavist/adaptavist.py
> +            return response.pop(0) or {}
I agree, I have updated the procedure to sort by 'id'.

2023-06-18 18:47 UTC, KanoB commented
Hi @Shutgun,

Sorry for taking so long in this. I have updated per your suggestions.
Let me know if you are ok with the changes.

Regards, K

2023-06-18 20:05 UTC, 2Fake approved these changes

2023-06-18 21:06 UTC, Shutgun commented
thx @KanoB , please let me check one more thing tomorrow: [pytest-adaptavist](https://github.com/devolo/pytest-adaptavist) is the main consumer of this package and I need to check the compatibility. If it works out, I will merge your change and release it :+1:

2023-06-21 15:10 UTC, Shutgun approved these changes

2023-06-21 15:10 UTC, merged